name: CI - Node.js backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando o código
        uses: actions/checkout@v3

      - name: Instalando Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalando dependências
        run: npm install

      - name: Testando build
        run: node servidor.js
